### ISSUE TITLE
no video and audio, when connect two users

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/jitsi_ynh#10]
When connecting a second user, there is no audio and video(black screen) from the other user - you just can see yourself.

used: Firefox 68, latest yunohost

With https://meet.jit.si/ it works, so it has nothing to do with firefox.
I checked the ports TCP/4443 and UDP/10000 and 4443 is open, 10000 is closed. I did not configure anything, but 4443 is already open.

I contacted my vServer provider and he tells me, that it is just me and my config, who can block ports. 
I do not think, that an extra DNS SRV entry is necessary. jit.si has no SRV entry in their dns config. (https://viewdns.info/dnsrecord/?domain=jit.si)
yunohost firewall says port 10000 is open.

Does this help? https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#running-behind-nat

**Comment by yalh76** [comment]
Have you tested with two Google Chrome ?

**Comment by yalh76** [comment]
I made some test from a local lan, with Chrome video is OK, with Firefox not....

**Comment by AkselRocks** [comment]
No, I did not test with Chrome, because I want to avoid Google services (I just realized, that Google Chrome is with 80% (!!!) the most popular web browser! https://www.w3schools.com/browsers/default.asp - that scares me!)

**Comment by AkselRocks** [comment]
The thing is: with https://meet.jit.si/ it works! So it has to be a thing of the jitsi installation.
different versions?
additional packages?

**Comment by AkselRocks** [comment]
Sounds like this problem here:
https://community.jitsi.org/t/no-video-and-audio-for-some-users/15540

**Comment by yalh76** [comment]
Well, I've made a test from outside of my network, with NAT, from two differents laptop, each one on a different internet connection
- test with Chrome is OK
- Test with 1 Chrome + 1 Firefox : Fail
- Test with 2 firefox : fail

**Comment by yalh76** [comment]
> 
> 
> No, I did not test with Chrome, because I want to avoid Google services (I just realized, that Google Chrome is with 80% (!!!) the most popular web browser! https://www.w3schools.com/browsers/default.asp - that scares me!)

I want to avoid too, but to move forward on tests, it would be helpfull

**Comment by AkselRocks** [comment]
I can not test with 2 Chrome browser,because I have only one laptop, but
- Mint firefox and android app: no video, no audio
- Mint firefox and IOS app: no video, no audio
- Android app and IOS: no video, audio only from ios to android
- Mint firefox, ANdroid ap and IOS: no video, no audio

Will make more tests with Chrome, when I use Windows

**Comment by AkselRocks** [comment]
Tests with Chrome:
- Windows Chrome and Android app: fail
- Windows Chrome and Android app and IOS app: IOS app asks for email and password!?

**Comment by AkselRocks** [comment]
I reactivated an old Laptop: 
Test with 2 Chrome fail (+ asking for password !?)

**Comment by AkselRocks** [comment]
is there any progress?

**Comment by yalh76** [comment]
Not for now, but still planned to work on it.

**Comment by AkselRocks** [comment]
Jitsi Meet is listed as Level 7, functioning and maintained.
Did I miss something?
Is there progress?
Does jitsi meet work for anybody else using not google chrome?

**Comment by yalh76** [comment]
Yes the automated package_check work and give the level 7. Event if I wasn't able to make it works with firefox...

I've tryed to update the package to a newer version but in that case even with chrome it doesn't work....

I've fully check the install steps without finding something missing...

Help will be appreciated...

**Comment by nitrogenix** [comment]
The firefox no sound / video issue is a known upstream bug: [https://github.com/jitsi/jitsi-meet/issues/4758](https://github.com/jitsi/jitsi-meet/issues/4758)

I can also confirm specific yunohost issue.
Tested between 2 chromium browsers and 2 chrome browsers (debian & fedora). All attempts fails on yunohost install. Everything works fine with [https://meet.jit.si/](https://meet.jit.si/)

**Comment by Lab-8916100448256** [comment]
I'm also having this issue. Not sure how I can help though

**Comment by pedro-nonfree** [comment]
Tried one-to-one conversation:

- Chrome-chrome (or chromium) does not works in the same LAN
- The other one changed to VPN and it worked

**Comment by plslvval** [comment]
I confirm with many tests on a server configuration behind NAT, only one to one P2P is working and requires chromiuim-browser (ubuntu case), i didn't drive tests on other platforms. It does not work in P2P with firefox.
That means that jitsi-videobridge video relay is not used or not accessible from external or not working.

**Comment by yalh76** [comment]
I've tryed to implement coturn, you can test it doing `yunohost app install https://github.com/YunoHost-Apps/jitsi_ynh/tree/coturn` and let me know...

**Comment by liberodark** [comment]
Have try coturn but same no video / no sound

![image](https://user-images.githubusercontent.com/4238928/79007520-9b8a6480-7b5b-11ea-9cdb-e6c9b178c30d.png)

**Comment by yalh76** [comment]
I'm currently working on #43. using .deb file instead of compiling to speed up installation and comparing a native installation on a stretch to this new branch. an idea given by @Tagadda

**Comment by liberodark** [comment]
Im go to try video branch

**Comment by yalh76** [comment]
for the test I made this night, audio/video is still only working between max 2 chromium.

**Comment by liberodark** [comment]
For what only 2 ?

**Comment by liberodark** [comment]
your last commit fail is for to add domain 

343874 DEBUG + yunohost domain add auth.jitsi.ynh.ovh
344476 WARNING The domain already exists

**Comment by yalh76** [comment]
yes it's because I don't have updated the readme. now you don't have to create all the sub-domains auth.*; conference.* jitsi-videobridge.* and focus.*
you must remove them doing `yunohost domain remove auth....." for each of them

**Comment by liberodark** [comment]
Yes have see that...

**Comment by yalh76** [comment]
> 
> 
> For what only 2 ? and for what chrome too ? on official website Firefox work and 2 or 10 is same that work.
> Something must be missing

Yes something is missing: make work jitsi-videobridge

**Comment by liberodark** [comment]
Probably use unstable version better no ?

**Comment by yalh76** [comment]
> 
> 
> Probably use unstable version better no ?

Nothing regarding an unstable version....

I have installed jitsi-meet on a stretch and audio/video is working for 2+ including firefox
That's why fix_video branch use the same .deb files just manually installed cause of prosody/metronome

**Comment by liberodark** [comment]
Step by step what is a diff on manual and your script ?

**Comment by yalh76** [comment]
idk... it would be solved if I knew...
For now the only differences I've seen:
- metronome instead of prosody
- unable to load muc_domain_mapper module in metronome

**Comment by liberodark** [comment]
https://jitsi.ynh.ovh/static/authError.html

![image](https://user-images.githubusercontent.com/4238928/79011766-055b3c00-7b65-11ea-8506-76fd2ce1da78.png)

**Comment by yalh76** [comment]
weird.. for me it works... you test between two chromium ?

**Comment by liberodark** [comment]
But same problem after fix this issue no video no sound only two

**Comment by yalh76** [comment]
yes... like the test I made that night... it's all around jitsi-videobridge.
Jitsi videobrige is used when you can't do p2p and you can't do p2p if you are more than 3 users or if you don't use Chromium because there is for now an issue for p2p in firefox...

**Comment by liberodark** [comment]
Your script only create : auth.jitsi.xxx

**Comment by yalh76** [comment]
yes other domain creation are not neeeded

**Comment by yalh76** [comment]
In #43 I've completly reworked the installation process to use .deb files and to be closest of a jitsi-meet installation aka https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md.
In this branch, no need to create all the sub-domains. If you created them, you should remove them doing `yunohost domain remove ....` for each domains.

I also disable p2p: https://github.com/YunoHost-Apps/jitsi_ynh/blob/51f7263ecc5c614702a03d53b3367df6990bb932/conf/config.js#L331-L338 to be sure even using chromium it will use jitsi-videobrige

For now, still doesn't work, seems something around jitsi-videobridge authentication on metronome. Can't find how to solve that.

**Comment by yalh76** [comment]
Still not solving that issue, seems like something around metronome IM Bosh and Jigasi/videobridge. 
I can't figure what's happen and quite bored of all the time / days I've worked on that.

Now it's level 0, not working and I won't try to solve that.

**Comment by AkselRocks** [comment]
I know these things can be very frustrating!

The least I can do is say thank you very much for trying and investing so much time and energy!

**Comment by plslvval** [comment]
I wonder if we are just not facing a limitation of metronome compared to prosody.
Jitsi is based on XMPP jingle protocol which is XEP-0166 and comparing xep documented as supported on both it seems XEP-0166 is only provided for prosody :
metronome xep list : https://metronome.im/supported-xeps-list : xep-0166 not found.
prosody xep list : https://prosody.im/doc/xeplist : xep-0166 listed.
So this would first require to validate outside yunohost that metronme can replace prosody and find where it has to be done.

I am still surprised it works in P2P, while it seems it would requires jingle too, but perhaps some part of jingle are provided as jitsi prosody plugin not fully working with metronome. This goes then beyond a simple port.

**Comment by alexAubin** [comment]
@Maranda : ping in case that could help make things move forward ... some people are again discussing this today and would really like to see jitsi working in the context of Yunohost. Sorry if you already discussed this in the past, but have you any information regarding plans to support XEP-0166 for Metronome ?

**Comment by maranda** [comment]
@alexAubin XEP-0166 doesn't need server support it's a client side spec so it would be always supported that's why it's not listed, beside I use Jingle VoIP with with Conversations all the time and works perfectly with Metronome.

Metronome already supports https://xmpp.org/extensions/xep-0215.html, and https://xmpp.org/extensions/xep-0278.html for TURN/STUN.

I would also like to point out https://github.com/YunoHost/issues/issues/1607 and that I don't get the reason to use Jitsi Meet to chat with 1v1. That's for multiparty chats.

I'm not sure what there's that would be missing comparing to Prosody on the Jingle VoIP department if it's the Jitsi Meet MUC plugins you mean I did also post a pull request to move things forward https://github.com/YunoHost-Apps/jitsi_ynh/pull/51#event-3455891648 but I didn't hear anything back on that department. 
I also know that the Jitsi people did internally patch Prosody to adapt it to work for Jitsi Meet, and some of those patches didn't get disclosed so at the time I didn't have nothing to look at, although being a while since I checked that may have changed.

Finally, I'm always eager to help @alexAubin even if I'm practically buried under a pile of work atm and have little time. But I seem to go forgotten by YunoHost people and then get blasted over with the usual once in a while "Oh it's Metronome's fault, let's switch to Prosody" and often the blame is found somewhere else after too.

So if you want me involved, involve me ;). 
... I just came to know about this issue today because you actually mentioned me.

**Comment by maranda** [comment]
Also when testing exotical plugins I do suggest enabling verbose logging, and checking for any possible traceback popping up and then eventually reporting the issue on https://github.com/maranda/metronome that for sure won't harm.

**Comment by yalh76** [comment]
> 
> 
> Also when testing exotical plugins I do suggest enabling verbose logging, and checking for any possible traceback popping up and then eventually reporting the issue on https://github.com/maranda/metronome that for sure won't harm.

Months ago, when enabling debug mode on metronome with exotical plugins, metronome crashed because the jitsi exotical plugins didn't manage debug mode ://// But @kay0u has restarted to work on it... Hopefully he will go one step further ^^

**Comment by maranda** [comment]
> > Also when testing exotical plugins I do suggest enabling verbose logging, and checking for any possible traceback popping up and then eventually reporting the issue on https://github.com/maranda/metronome that for sure won't harm.
> 
> Months ago, when enabling debug mode on metronome with exotical plugins, metronome crashed because the jitsi exotical plugins didn't manage debug mode ://// But @kay0u has restarted to work on it... Hopefully he will go one step further ^^

I'd like to see that in practice since doing the same work on the same plugins, with debug logs enabled didn't produce any crash... As usual didn't see any ticket appearing into https://github.com/maranda/metronome issue tracker also 😺

**Comment by yalh76** [comment]
> 
> 
> > > Also when testing exotical plugins I do suggest enabling verbose logging, and checking for any possible traceback popping up and then eventually reporting the issue on https://github.com/maranda/metronome that for sure won't harm.
> > 
> > 
> > Months ago, when enabling debug mode on metronome with exotical plugins, metronome crashed because the jitsi exotical plugins didn't manage debug mode ://// But @kay0u has restarted to work on it... Hopefully he will go one step further ^^
> 
> I'd like to see that in practice since doing the same work on the same plugins, with debug logs enabled didn't produce any crash... As usual didn't see any ticket appearing into https://github.com/maranda/metronome issue tracker also 😺

it's because it wasn't a metronome issue but more a "exoticals modules"" issue

**Comment by maranda** [comment]
But I worked on the same "exotical modules" (hence my pull request posted earlier) in Metronome... with debug logging enabled and without crashes 🙂

**Comment by nick773312** [comment]
seems like jitsi is still broken here in 2025.. this is crazy
