### ISSUE TITLE
Jitsi Prosody install has cert issues

### ISSUE THREAD

**Issue by fossmanjack** [YunoHost-Apps/jitsi_ynh#117]
### Describe the bug

Jitsi appears to try to replace metronome with prosody, but in my case the prosody install had some kind of certificate issue and wouldn't accept connections.  I ended up disabling prosody and restarting metronome, but I think that might have broken Jitsi?

### Context

- Hardware: VPS
- YunoHost version: 11.1.21.4
- I have access to my server: SSH/Webmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: Jitsi 2.0.8319~ynh1
- If upgrading, current package version: N/A

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install jitsi
    ```

### Expected behavior

Presumably prosody should take over for metronome?  I don't know what the "expected behavior" was, I wasn't expecting a prosody install at all

### Logs

https://paste.yunohost.org/raw/ifodukipas

journalctl:

```journal

Jul 06 18:02:00 mydomain.tld prosody[20226]: portmanager: Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281                                                                                            Jul 06 18:02:00 mydomain.tld prosody[20226]: portmanager: Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281
```

Snippet from prosody.log:

```log
Jul 07 01:14:20 s2sin561c39a279d0       info    Incoming s2s stream domain.tld->mydomain2.tld closed: This host does not serve mydomain2.tld                                                                                                                     Jul 07 01:14:23 s2sin561c397f4040       info    Incoming s2s stream domain.tld->mydomain2.tld closed: This host does not serve mydomain2.tld
```

**Comment by yalh76** [comment]
Jitsi require prosody
Prosody and Metronome use the same TCP port so the can't work together.

If you disable prosody, jitsi won't work.

At the first install of prosody, as there is no domain declared, there is no certificate to be used.

But later during the install, prosody is configured, certificate is generated and service prosody is restarted
