### ISSUE TITLE
Error: You have been disconnected

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/jitsi_ynh#120]
### Describe the bug

I just installed Jitsi for the first time. Whenever I enter in a meeting room there is the error message "You have been disconnected". There are also several errors in browser console.
![image](https://github.com/YunoHost-Apps/jitsi_ynh/assets/19874562/26dfd785-3753-42a3-90ea-81ece59b0e49)
![image](https://github.com/YunoHost-Apps/jitsi_ynh/assets/19874562/016026df-42c6-4db2-a9f8-c8e5fe9c5aaf)

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.0.8719~ynh2

### Steps to reproduce

Just enter a random meeting.

### Expected behavior

I should stay connected to the meeting.

### Logs
This is the log from jitsi-videobridge service: https://paste.yunohost.org/igeyekojiw.sql 
Relevant part is probably this.

```
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve auth.meet.jitsi-domain.tld</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by yalh76** [comment]
try:
```
systemctl stop metronome.service --quiet
systemctl disable metronome.service --quiet
systemctl restart prosody.service --quiet
```

metronome.service should have been restarted after an upgrade of metronome

**Comment by CodeShakingSheep** [comment]
> try:
> 
> ```
> systemctl stop metronome.service --quiet
> systemctl disable metronome.service --quiet
> systemctl restart prosody.service --quiet
> ```
> 
> metronome.service should have been restarted after an upgrade of metronome

This seems to work, thank you :) However, I didn't get the explanation. So, metronome service should stay disabled?

**Comment by yalh76** [comment]
yes metronome should stay disabled

metronome is a fork of prosody, so the work on the same tcp port and can't work on the same server
