### ISSUE TITLE
Disable Metronome

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/jitsi_ynh#126]
Jitsi requires Prosody and if Metronome is running then Jitsi cannot be used. Prosody and Metronome conflict. You would have to stop Metronome and restart Prosody in order for Jitsi to work. On my system Metronome always keep enabling itself...

`systemctl disable metronome.service` doesn't seem to help. 

```
metronome.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable metronome

```

Many have complained about this in the past, they see a "rejoin" message that keeps on looping. This is the reason why....

**Comment by OniriCorpe** [comment]
Hi!

The packages’s docs now asks to uninstall metronome before install jitsi :)
