### ISSUE TITLE
Jitsi Meet isn't working with Jitsi Android app with self-hosted instance

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/jitsi_ynh#134]
### Describe the bug

In the official Jitsi Meet Android app (downloaded from FDroid) no meetings from the YNH hosted Jitsi instance can be started. After creating / joining a meeting in the app, it goes into disconnected / trying to reconnect loop. Has already been described here: https://forum.yunohost.org/t/problems-with-jitsi-app-on-mobile-and-config-js-it-seems-to-be-solved/26849

### Context

- Hardware: VPS bought online
- YunoHost version: x.x.x
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.0.9111~ynh1

### Steps to reproduce

1. I installed the Jitsi instance
2. Created a room with my login and password
3. Entered the room via browser with another desktop device
4. Entered the room via browser with a mobile device
5. Tried to enter the room with Jitsi Android and with no success

### Expected behavior

Jitsi meeting should work in Android app.

### Logs

Couldn't find any related logs.
Edit: Found out it's related to this JS error.
![image](https://github.com/YunoHost-Apps/jitsi_ynh/assets/19874562/016026df-42c6-4db2-a9f8-c8e5fe9c5aaf)

**Comment by OniriCorpe** [comment]
Your PR is now in testing ^w^
