### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/jitsi_ynh#153]
### Describe the bug

Upgrade failed. The reason is that directory `/var/www/jitsi/jitsi-jicofo/jicofo` wasn't empty. See logs.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.30.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: *2.0.9646*

### Steps to reproduce

Just hit the "Upgrade" button in webadmin.

### Expected behavior

Jitsi should be upgraded succcessfully.

### Logs

https://paste.yunohost.org/raw/basagoxuwi

**Comment by binuts** [comment]
Upgrade failed.
My logs : https://paste.yunohost.org/raw/sagodoguxu

**Comment by yekibud** [comment]
Per the other thread, installing from testing works, if you want a work-around https://github.com/YunoHost-Apps/jitsi_ynh/issues/154#issuecomment-2430757558

**Comment by CodeShakingSheep** [comment]
Still the same for me when wanting to upgrade to the latest version on master: https://paste.yunohost.org/raw/dutuwodoxi
