### ISSUE TITLE
Incomplete Readme: "Jitsi requires the ports TCP/4443 and UDP/10000 to be redirected to your YunoHost"

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/jitsi_ynh#22]
Please add missing installations instructions to the Readme. Thanks!

**Comment by yalh76** [comment]
What are the missing installations instructions ?
Feel free to make a PR to discuss that point.

**Comment by TheNomad11** [comment]
how to make the redirect as quoted in the title: ""Jitsi requires the ports TCP/4443 and UDP/10000 to be redirected to your YunoHost"

**Comment by yalh76** [comment]
That's already in the YunoHost documentation =>https://yunohost.org/#/isp_box_config_en
