### ISSUE TITLE
"Invalid cookie header:" Temporary troubles while installing jitsi_ynh :)

### ISSUE THREAD

**Issue by JRelland** [YunoHost-Apps/jitsi_ynh#33]
Hi, first thank you for Jitsi on YNH.

let me mention this which is not necessarly important (just frightening for our configuration) as our JItsi instance seems to work on YNH Powered by YunoHost 3.6.5.3 (stable) / OVH SSD 1 :).

the "permanent" message was:
```
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Fri, 19 Mar 2021 14:02:58 GMT; HttpOnly; Secure". Invalid 'expires' attribute: Fri, 19 Mar 2021 14:02:58 GMT

Mar 19, 2020 3:02:59 PM org.apache.maven.wagon.providers.http.httpclient.client.protocol.ResponseProcessCookies processCookies

WARNING: Invalid cookie header: "Set-Cookie: _octo=GH1.1.426984661.1584626578; Path=/; Domain=github.com; Expires=Fri, 19 Mar 2021 14:02:58 GMT; Secure". Invalid 'expires' attribute: Fri, 19 Mar 2021 14:02:58 GMT

Mar 19, 2020 3:02:59 PM org.apache.maven.wagon.providers.http.httpclient.client.protocol.ResponseProcessCookies processCookies
```
To stop this loop (the bin did not work) I've been obliged to run again the admin url.
After some minutes, I've been able to reach my admin panel (Ouf! as we say in French!)

Just a question.
In your Readme file, you mention the port redirection. But this is not necessary for a VPS hosting ?!

Thank you for any comment.

José

**Comment by pedro-nonfree** [comment]
happened the same to me (instance in ovh)

It spend like 5-10 minutes stuck on that message and finally could continue

**Comment by yalh76** [comment]
> Just a question.
> In your Readme file, you mention the port redirection. But this is not necessary for a VPS hosting ?!

On a VPS you don't need to do port redirection, just check that thoses ports are open from internet
