### ISSUE TITLE
password required

### ISSUE THREAD

**Issue by pedro-nonfree** [YunoHost-Apps/jitsi_ynh#35]
When I try to join a room in my jitsi server asks for the user and password of yunohost [1]. That's bad if I want to invite a guest to have a conversation. The default configuration allows guests to join rooms and looks like you changed the default config. Where can I re-change the config?

Thanks

[1] ![image](https://user-images.githubusercontent.com/39959198/78399882-08e74400-75f6-11ea-89cb-69268229c650.png)

**Comment by yalh76** [comment]
which branch did you installed?

**Comment by liberodark** [comment]
same and is on master & corturn

**Comment by pedro-nonfree** [comment]
I have a yunohost stable instance and I installed it using the button and some tweaks (like generating that weird subdomains)

**Comment by plslvval** [comment]
i confirm i have this problem too, can be visible at https://teleconf.slvtv.fr

**Comment by Saimyx** [comment]
I had the same problem with last master version, but a ctrl+R has solved the problem.
Maybe ? :)

**Comment by airwoodix** [comment]
I have the same problem on the `fix_video` branch (with `metronome 3.14` installed manually). The first user can create the room, a second user needs to enter credentials (similar to what @plslvval reports). LDAP credentials do not work (unless I mistyped).
From the metronome configuration, this makes little sense. Any idea what is going on here?

**Comment by airwoodix** [comment]
@yalh76 can you reproduce this? Seems to be present in multiple branches and, in my experience, defeats the whole purpose of jitsi-meet. Thanks.
