### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by 3615pipou** [YunoHost-Apps/jitsi_ynh#40]
When I go to the jitsi meet page it directly launch a conference without proposing me to choose a room name. 

Why the welcome page isn't display as we can see it at this end of this video ?
https://jitsi.org/news/new-tutorial-installing-jitsi-meet-on-your-own-linux-server/

https://www.youtube.com/watch?v=8KR0AhDZF2A

**Comment by yalh76** [comment]
It's because `enableWelcomePage: true,` is not activated in https://github.com/YunoHost-Apps/jitsi_ynh/blob/master/conf/config.js
