### ISSUE TITLE
ERROR 404 during installation

### ISSUE THREAD

**Issue by MensoifG** [YunoHost-Apps/jitsi_ynh#52]
I just encountered such problem during installation
2020-06-17 19:36:16,041: WARNING - https://download.jitsi.org/jitsi-videobridge/linux/jitsi-videobridge-linux-x64-1130.zip:
2020-06-17 19:36:16,042: DEBUG - 2020-06-17 19:36:16 ERROR 404: Not Found.'
2020-06-17 19:36:16,042: WARNING - 2020-06-17 19:36:16 ERROR 404: Not Found.

**Comment by yalh76** [comment]
It's because they removed that file ....

**Comment by Yajo** [comment]
Maybe it would be better to use their deb packages? https://download.jitsi.org/stable/

**Comment by yalh76** [comment]
all.deb   include arm build.

Thanks, it's what I tryed at :https://github.com/YunoHost-Apps/jitsi_ynh/pull/43

**Comment by paalwilliams** [comment]
> It's because they removed that file ....

ok - so what are we supposed to do to install? This doesn't seem like a helpful solution.

**Comment by MensoifG** [comment]
Thanks for your answers and still no solution then.

**Comment by stevefloyd** [comment]
> I just encountered such problem during installation
> 2020-06-17 19:36:16,041: WARNING - https://download.jitsi.org/jitsi-videobridge/linux/jitsi-videobridge-linux-x64-1130.zip:
> 2020-06-17 19:36:16,042: DEBUG - 2020-06-17 19:36:16 ERROR 404: Not Found.'
> 2020-06-17 19:36:16,042: WARNING - 2020-06-17 19:36:16 ERROR 404: Not Found.

Exact same error when I try to install this package.
