### ISSUE TITLE
Installation failed - unknown Mail Domain 'auth.jitsi.domain.tld

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/jitsi_ynh#6]
installation does not run through.

log: https://paste.yunohost.org/raw/uzevodeyer

diagnose: https://paste.yunohost.org/rixadecihu

**Comment by yalh76** [comment]
@AkselRocks 

;)

![jitsi](https://user-images.githubusercontent.com/30271971/62485674-a8c9a500-b7bd-11e9-9f8c-c7e51e2420c2.PNG)

The required domains and certificates must be created and configured before you install jitsi_ynh

**Comment by AkselRocks** [comment]
Because jitsi is different/special to other apps, maybe it is a good idea to put this information to the site before installing. 

Is it possible, that the additional domains are created automatically by yunohost?
And like in DNS configuration from other domains: to show how the dns configuration should look like?

That would make things much easier for non-professionals.

**Comment by yalh76** [comment]
I can add a first question during install to ask if the required domains are created.

About the additional domains creation: it was a desicion during the PR: https://github.com/YunoHost-Apps/jitsi_ynh/pull/4#discussion_r305083163

I let you read the reasons of the decision. But we can discuss it if you want.

**Comment by AkselRocks** [comment]
I am not sure, if I understand all the reasons for the decision, but maybe the part with letsencrypt (5 domains per week) is different: 
https://github.com/YunoHost-Apps/jitsi_ynh/pull/4#discussion_r310752492

**Comment by AkselRocks** [comment]
TCP/4443 and UDP/10000 redirected to which domain(s)? 
How should the additional dns entries look like?

**Comment by yalh76** [comment]
> I am not sure, if I understand all the reasons for the decision, but maybe the part with domain creation and letsencrypt (5 domains per week) is different:

Yes, exactly the point :)

**Comment by yalh76** [comment]
> 
> 
> TCP/4443 and UDP/10000 redirected to which domain(s)?
> How should the additional dns entries look like?

Need to be redirected directly to you YunoHost

**Comment by AkselRocks** [comment]
TCP/4443 and UDP/10000 redirected to which domain(s)? 
How should the additional dns entries look like?

> > I am not sure, if I understand all the reasons for the decision, but maybe the part with domain creation and letsencrypt (5 domains per week) is different:
> 
> Yes, exactly the point :)

I remember the 5 per week limitation, but i installed more than 5 within the last week.

I think they changed the limitation to 50 per week: https://letsencrypt.org/docs/rate-limits/
Only **duplicate** certificates are 5 per week. So if something goes wrong with the installation of jitsi_ynh (and the certificates were already installed), there are "just" 5 tries per week, right?

**Comment by yalh76** [comment]
> I remember the 5 per week limitation, but i installed more than 5 within the last week.
> 
> I think they changed the limitation to 50 per week: https://letsencrypt.org/docs/rate-limits/
> Only **duplicate** certificates are 5 per week. So if something goes wrong with the installation of jitsi_ynh (and the certificates were already installed), there are "just" 5 tries per week, right?

Yes, if jitsi_ynh handle domain and certificate creation, you would have only 5 tries peer week.

**Comment by AkselRocks** [comment]
And if the installation process works, you just need **one** try! 

So I think it is possible and a good idea to do creating and certification by yunohost/script. (Maybe with a warning, that the admin only can install and remove jitsi_ynh 5 times within a week because of the limitation of letsencrypt.)

That is, what yunohost is good for: doing installation process with a script, right?

**Comment by AkselRocks** [comment]
After manually create and certificate the additional domains, the problem disappears.

**Comment by YamineRL** [comment]
Could you describe the steps to add these subdomains and certificates?  (I'm with GoDaddy but anything will help)

**Comment by yalh76** [comment]
> 
> 
> Could you describe the steps to add these subdomains and certificates? (I'm with GoDaddy but anything will help)

https://yunohost.org/#/domains_en

**Comment by gorfreed** [comment]
@yalh76 Maybe you should check how many people are actually capable of successfully using your script here. I have installed Yunohost on multiple systems, the Jitsi-Meet install never works out of the box as it should (this is what Yunohost was created for after all!). @AkselRocks were you successful with your install in the end?

**Comment by yalh76** [comment]
> 
> 
> @yalh76 Maybe you should check how many people are actually capable of successfully using your script here. I have installed Yunohost on multiple systems, the Jitsi-Meet install never works out of the box as it should (this is what Yunohost was created for after all!). @AkselRocks were you successful with your install in the end?

Maybe, if you think you can do it better, you should make a PR.

**Comment by AkselRocks** [comment]
@gorfreed yes, I think the installation works out. That was 8 months ago and because of other problems (I don't want to use google chrome and firefox has some issues with jitsi) AND I am not a programmer (and yunohost is a project of voluntarily and unpaid people!) I had to find another solution.
