### ISSUE TITLE
Seems like the camera and mic are not working for the other participants

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/jitsi_ynh#62]
Hardware: VPS bought online
    YunoHost version: 4.3.6.2 (stable).
    I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | ...
    Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

I can see my camera/mic working, but the others cannot. And I cannot see theirs. Works to connect, but no audio/video is sent to the other participants.

**Comment by yalh76** [comment]
is it the same as #60 ?

**Comment by tio-trom** [comment]
Perhaps thats the issue:

```
Port 4443 is not reachable from outside.

    Exposing this port is needed for [?] features (service jitsi-videobridge)
```

So we can close this and more to the other issue.
