### ISSUE TITLE
Not working until a chrome user enter in the room 

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/jitsi_ynh#74]
### Describe the bug

just after the first install and 1rst room creation
no video and sound until a chrome user enter in the room

### Context

- Hardware: odroid hc1 armhf(v7) 2Gb RAM 
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: inside lxc container
- Using, or trying to install package version/branch: master
- If upgrading, current package version: NA

### Steps to reproduce

- Create a room with firefox
- Enter in the room with android app
-> no sound not video both way
- enter in the room with chrome
-> chrome user and firefox are visible android not for chrome and firefox (reverse android can't see chrome and firefox)
- quit and join again from android
-> all works

- close room in all terminals
- Create a room with firefox
- Enter in the room with android app
->  all works

**Comment by AkselRocks** [comment]
I see similar issue also in a native jitsi installation:
2 firefox user -> unstable: sound stable yes, video unstable.
1 firefox user and 1 Linux jitsi app user (=chrome based browser) -> sound and video stable.

Is this a jitsi issue and not a ynh issue?

**Comment by rosbeef** [comment]
humm 
all right. maybe i should post there
i will close
