### ISSUE TITLE
Add jibri

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/jitsi_ynh#75]
### Describe the bug

livestream not working

### Context

no specific context because not implemented

### Steps to reproduce

no step to reproduce because not implemented

### Expected behavior

Create a module app to add Share live streaming with peertube/youtube ... througth rtmp link, 
Good for small companies and CHATONS to record conferences easily and New wave of peertubers.

### Logs

https://github.com/jitsi/jibri

**Comment by tio-trom** [comment]
I was wondering why the livestream doesnt work...thanks for the heads-up. I've heard jibri is difficult to setup https://community.jitsi.org/t/tutorial-jibri-overview-troubleshooting-tips-tricks-solve-your-jibri-problems-quickly/86054

**Comment by theRAGEhero** [comment]
It would be awesome to add Jibri!

**Comment by yalh76** [comment]
As describe in the requirements : https://jitsi.support/wiki/setting-up-jibri-jitsi-guide#prerequisites

jibri doesn't really fit on a YunoHost

`Jibri requires a modern processor with virtualization support, at least 4GB of RAM (8GB recommended), and a sound and video card capable of capturing the audio and video to be streamed or recorded`

`Jibri instance can only handle one recording or streaming job at a time`
