### ISSUE TITLE
 Port 10000 is not reachable from outside

### ISSUE THREAD

**Issue by rouja** [YunoHost-Apps/jitsi_ynh#77]
Hi,

The yunohost console reports : "Port 10000 is not reachable from outside." 

I think it's a false positif. Because jitsi is listening in UDP on this port : 
```
UNCONN 0      0                 [::ffff:91.121.133.42]:10000             *:*     users:(("java",pid=23209,fd=147))
```

Maybe we should remove this port from the check list ?

I'm new to yunohost but I think that the solution could be just to change this line in the install script :
```
yunohost service add $app-videobridge --log "/var/log/$app/$app-videobridge.log" --needs_exposed_ports $port $port_videobridge
```
By
```
yunohost service add $app-videobridge --log "/var/log/$app/$app-videobridge.log" --needs_exposed_ports $port
```

What do you think ?

**Comment by rosbeef** [comment]
Related to #60 
Jitsi open the port only when it using it
