### ISSUE TITLE
Just a question.... Is it possible to have metronome working WITH jitsi???

### ISSUE THREAD

**Issue by bjarkan** [YunoHost-Apps/jitsi_ynh#78]
I know, it says that it deactivate metronome, but, just in case that metronome is mandatory... is there a work around??

I don't know... maybe another instance of yunohost just with this app, and redirect from the first machine the domain jitsi.domain.net to the machine with yunohost and jitsi?

Could it be a solution?

Any ideas?

**Comment by yalh76** [comment]
No, it's not possible to have metronome working with jitsi, tryed during weeks on #58, you can also check #29 #10 since August 2019 to February 2021

If you think, you can manage that, feel free to do a PR

**Comment by csolisr** [comment]
Is it normal that the automatic diagnosis keeps claiming that the service Metronome is dead? Is it safe to disable this warning?

**Comment by yalh76** [comment]
Yes it's safe to disable the warning
