### ISSUE TITLE
Installation failed - /etc/metronome/conf.d/jitsi.domain.tld.cfg.lua - file not found

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/jitsi_ynh#8]
there are cfg.lua files for all the additional domains, but not for the chosen "install domain" (jitsi.domain.tld).

log: https://paste.yunohost.org/raw/osejukuser 

(I did not configure the ports on DNS (TCP/3444 and UDP/10000) yet, but I guess, that has nothing to do with this problem, right?)

**Comment by yalh76** [comment]
That issue is because you had a first failed install, and it didn't restore the metronome file.
I will do a PR to solve that.

For now, you have to recreate /etc/metronome/conf.d/treffen.aksel.rocks.cfg.lua with the content:
```
VirtualHost "treffen.aksel.rocks"
  ssl = {
        key = "/etc/yunohost/certs/treffen.aksel.rocks/key.pem";
        certificate = "/etc/yunohost/certs/treffen.aksel.rocks/crt.pem";
  }
  authentication = "ldap2"
  ldap = {
     hostname      = "localhost",
     user = {
       basedn        = "ou=users,dc=yunohost,dc=org",
       filter        = "(&(objectClass=posixAccount)(mail=*@treffen.aksel.rocks))",
       usernamefield = "mail",
       namefield     = "cn",
       },
  }
```

**Comment by AkselRocks** [comment]
created the file, changed the ownership to metronome:metronome and the installation worked like charme! :-)
