### ISSUE TITLE
jitsi-jicofo cannot start

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/jitsi_ynh#81]
Let me start by saying that I edited some files, as it was suggested here, to be able to enable Jitsi for everyone not just logged in users. I edited `/etc/jitsi/jicofo/jicofo.conf`  and removed
```
authentication: {
			
    enabled: true
			
    type: XMPP
			
    login-url: __DOMAIN__
			
 }
```
Edited `/etc/jitsi/meet/call.trom.tf-config.js` commented out  `        anonymousdomain: 'guest.__DOMAIN__', `

And edited ` /etc/prosody/conf.avail/call.trom.tf.cfg.lua  ` to replace 

```
  authentication = "ldap"
			
    ldap_server = "localhost"
			
    ldap_filter = "(uid=$user)"
			
    ldap_scope = "subtree"
			
    ldap_base = "ou=users,dc=yunohost,dc=org"
			
    ldap_mode = "bind"
```
 With ` authentication = "anonymous" ` plus delete 

```
VirtualHost "guest.__DOMAIN__"
			
    authentication = "anonymous"
			
    c2s_require_encryption = false
```

Now all worked fine until the last update. What changed? This is the log https://paste.yunohost.org/aratayarag . I mainly see
```
Jicofo 2022-06-17 22:54:21.487 WARNING: [1] CmdLine.parse#117: Skipped empty cmd line argument: port=
Jicofo 2022-06-17 22:54:21.488 WARNING: [1] CmdLine.parse#117: Skipped empty cmd line argument: secret=
```

Can anyone help me out? Would be quite useful to be able to have Jitsi available for everyone not just logged in users.

 Thanks a  bunch!

**Comment by yalh76** [comment]
Can you check `/etc/__APP__/jicofo/config` to look if `JICOFO_PORT` and `JICOFO_SECRET` are provided

**Comment by yalh76** [comment]
Can you try to upgrade to 1.0.6155~ynh2 ?

**Comment by tio-trom** [comment]
Upgraded and now it works. However no video stream. I see

```
Port 10000 is not reachable from outside.

    Exposing this port is needed for [?] features (service jitsi-videobridge)
```

Despite being open in the firewall settings:
![2022-06-18_18-39](https://user-images.githubusercontent.com/38043315/174448289-3a913354-a0fb-4a00-b25d-a6360d335102.png)

**Comment by tio-trom** [comment]
Oh well now seems to work despite that error... I guess I can close this issue. Thank you very much!
