### ISSUE TITLE
Dark screen with Jitsi Meet Electron desktop app

### ISSUE THREAD

**Issue by sushidave** [YunoHost-Apps/jitsi_ynh#85]
### Describe the bug

When we use YunoHost Jitsi server with **Jitsi Meet Electron desktop app** we get a dark screen after entering a room name / URL. No login/authentication window, no video screen in the background. 

![jitsi-meet-electron-dark-screen-2022-07-18](https://user-images.githubusercontent.com/17728384/179560616-f1027a32-dd1f-48a8-a1b3-2b3b3062abf6.png)

We also tried the solution mentioned at #63 (added code in nginx config) but to no avail.

However, it works with the Android app and in the browser.

On the YunoHost Jitsi app page it says that it can only be used using Chrome/Chromium (like Iron) or Firefox (since version 76) and is limited to two participants: https://yunohost.org/en/app_jitsi. Is this still up to date?

### Context

- Jitsi Meet Electron: 2022.6.1
- Hardware: VPS bought online
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH, through the webadmin, direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

1. Start Jitsi Meet Electron
2. Enter the room name / URL and hit Enter.
3. Dark screen

### Expected behavior

Steps 1 to 2: see above
3. Login or video screen appears.

### Logs

No entries in the log for Electron. However, there are entries for other working sessions (Android, browser).

**Comment by yalh76** [comment]
have you tried with last version of jitsi ?

**Comment by sushidave** [comment]
@yalh76 Thanks for your reaction. I tried now with version 2022.9.1, same result.

**Comment by yalh76** [comment]
so it comes from somewhere else ... if you have some logs from Jitsi Meet Electron and jitsi_ynh, would be helpfull

**Comment by hermann-san** [comment]
same for me. I still get a black screen. with 22.9.1
There are no log-entries for the desktop-app session in YH jitsi-jicofo service. There are YH-logs for the Firefox browser session  though  in YH jitsi-jicofo (which works normal). 

THere are lot's of these in the YH jitsi-videobridge  service logs, even when there is not meeting. one every minute. It doesn't seem to be related to the issue IMO.
`JVB 2022-10-19 22:25:09.222 INFO: [22] VideobridgeExpireThread.expire#140: Running expire()`

I've not found logs for flatpak install of Electron. Do you happen to know how to get the logs?

I find it very strange that not a single entry is generated for the Electron session on the YH-server in  jitsi-jicofo service. It implies that something else is blocking the session, even before it come's to Jitsi.
However, FIrefox/Brave browser session, with the same Jisi installation works fine.

**Comment by yalh76** [comment]
Have you tried from a more recent version ?

**Comment by sushidave** [comment]
@yalh76 Thank you for asking. For me, it works with Jitsi Meet Electron 2024.10.0. 
@hermann-san Does it work for you and what's the YunoHost version?

**Comment by hermann-san** [comment]
same for me with that Version 2024.10.0 @sushidave   . It works
I guess the issue can be closed then.
