### ISSUE TITLE
[BUG] Unable to install 

### ISSUE THREAD

**Issue by vsatmydynipnet** [YunoHost-Apps/jitsi_ynh#88]
Jitsi currently fails to install on a fresh setup version 11 Yunohost because it wants prosody >= 4.3.0 .  Requirements are not met for Prosody error, then deinstalls thjings again.

Thank you for changing the package

**Comment by yalh76** [comment]
can you share the install log with yunopaste ?

Because test on yunohost 11.0.9.13 looks perfect => https://github.com/YunoHost-Apps/quizzes_ynh

**Comment by vsatmydynipnet** [comment]
This is 11.0.9.14

https://paste.yunohost.org/raw/ekibehiqis

**Comment by yalh76** [comment]
Can you try to manually install prosody ? 
`yunohost app install prosody`

**Comment by taneharre** [comment]
I had the same problem. Disabling metronome and manually installing prosody allowed me to install. Just tested and it works!
https://paste.yunohost.org/raw/ezopamucaz
