### ISSUE TITLE
Jitsi doesn't work after upgrade

### ISSUE THREAD

**Issue by dhuschde** [YunoHost-Apps/jitsi_ynh#95]
### Describe the bug
Jitsi stopped working after I upgraded to the latest version. It still doesn't work after reinstalling or using the Backup created before the update.
![image](https://user-images.githubusercontent.com/85834680/205170085-25f2959f-c493-44d1-b7aa-af3aeab85349.png)

### Context

- Hardware: *VPS bought online at Contabo*
- YunoHost version: 11.0.10.2 (stable).
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - I installed Docker and Restreamer (https://datarhei.github.io/restreamer/)
- Using, or trying to install package version/branch: Jitsi: 2.0.8044-ynh1 | Prosody: 0.11.13-ynh3

#### Videobridge
https://paste.yunohost.org/uzeluliboy

#### Jicofo
https://paste.yunohost.org/yicekegiwe

#### Prosody
https://paste.yunohost.org/ovededucip

**Comment by Frereneo** [comment]
Hello, I have the same problem since the update.
Sincerely,

**Comment by rouja** [comment]
Hello,

I had the same issue with the last version. To make Jitsi works again, I installed a previous version :


1- Uninstall jitsi and prosody (if it's not uninstalled automatically)
2- Install a specific version (https://github.com/YunoHost-Apps/jitsi_ynh/commit/d1579c1f9d389ee9c255470670d9bf7b27b6d776)
```
 sudo yunohost app install https://github.com/YunoHost-Apps/jitsi_ynh/tree/d1579c1f9d389ee9c255470670d9bf7b27b6d776
 ```
Sincerely,

**Comment by rouja** [comment]
I just noticed some change in /var/www/jitsi/jitsi-jicofo/jicofo.sh between the two versions. But I can't figure out how to fix the issue :(

**Comment by tio-trom** [comment]
Same here. Stopped working. Restoring did not help for some reason.

**Comment by Frereneo** [comment]
Hello @tio-trom ,
The solution proposed by @rouja (https://github.com/YunoHost-Apps/jitsi_ynh/issues/95#issuecomment-1339143598), allows to go back to the version before the update.
But it doesn't seem to solve the update

**Comment by tio-trom** [comment]
> Hello @tio-trom , The solution proposed by @rouja ([#95 (comment)](https://github.com/YunoHost-Apps/jitsi_ynh/issues/95#issuecomment-1339143598)), allows to go back to the version before the update. But it doesn't seem to solve the update

Yes I did just that but failed to work. Same issue. I had to restore a system snapshot to restore.

**Comment by Frereneo** [comment]
> > Hello @tio-trom , The solution proposed by @rouja ([#95 (comment)](https://github.com/YunoHost-Apps/jitsi_ynh/issues/95#issuecomment-1339143598)), allows to go back to the version before the update. But it doesn't seem to solve the update
> 
> Yes I did just that but failed to work. Same issue. I had to restore a system snapshot to restore.

Oh, ok, sorry. I had misunderstood.

**Comment by tio-trom** [comment]
No problem at all! :)

**Comment by rouja** [comment]
Hi,

I think I fixed the issue with the last version. In /etc/jitsi/jicofo/config we have :
```
# Jitsi Conference Focus settings
# sets the host name of the XMPP server
JICOFO_HOST=$REDACTED

# sets the XMPP domain (default: none)
JICOFO_HOSTNAME=$REDACTED

# sets the XMPP domain name to use for XMPP user logins
JICOFO_AUTH_DOMAIN=$REDACTED

# sets the username to use for XMPP user logins
JICOFO_AUTH_USER=$REDACTED

# sets the password to use for XMPP user logins
JICOFO_AUTH_PASSWORD=$REDACTED
```
To fix the issue we need to report the value in /etc/jitsi/jicofo/jicofo.conf in the xmpp section:
```
  xmpp: {
    client: {
      enabled: true #Add this line
      hostname: localhost #Add this line
      client-proxy: $REDACTED #Do not change this line
      xmpp-domain: $JICOFO_HOSTNAME #Add this line and replace the variable by the value from /etc/jitsi/jicofo/jicofo.conf 
      domain: $JICOFO_AUTH_DOMAIN #Add this line and replace the variable by the value from /etc/jitsi/jicofo/jicofo.conf
      user: $JICOFO_AUTH_USER #Add this line and replace the variable by the value from /etc/jitsi/jicofo/jicofo.conf
      password: $JICOFO_AUTH_PASSWORD #Add this line and replace the variable by the value from /etc/jitsi/jicofo/jicofo.conf
    }
```

I hope that it will help to fix jitsi on yunohost.

**Comment by Frereneo** [comment]
Hello @rouja ,
Thanks for this detail :).
Does the update in the YNH application management do this correction by itself, or do you have to do it yourself?
thank you again !

**Comment by rouja** [comment]
Hello,

The update will not do the correction by itself. You have to do the change yourself. But if it's fix the problem for you too, if I find time, I will try to fix the YNH packaging and submit a PR.

**Comment by Frereneo** [comment]
Re,
The proposed solution corrects the anomaly.
Congrats :dancers: !!

**Comment by dalgwen** [comment]
Thank you for the fix !

**Comment by hermann-san** [comment]
recently I've updated Jitsi and it appears to have reintroduced the issue after the update.  I did apply the [proposed solution above,](https://github.com/YunoHost-Apps/jitsi_ynh/issues/95#issuecomment-1349708228) but it didn't help.

My solution was die uninstall Jitsi and uninstall Prosody as well. Then re-install Jitsi and it worked again.

There seems to be something in the Jitsi Update that can break an existing installation.

**Comment by tio-trom** [comment]
So this needs to be fixed because the issue is from Metronome. If the Metronome service is active then you cannot use JItsi. And you will have to stop Metronome and restart Prosody.

Problem is even trying to kill the Metronome service for good it somehow keeps on resurrecting....idk what to do about this...
